CONFIG_GPIO=y

# LooUQ host boards have various add-on functionality connected via
# the "host extension" interface (HX). This is implemented with I2C
# typically assigned to I2C3 in the devicetree board overlay.
CONFIG_I2C=y

# Most LooUQ host boards have a TI LED controller for RGB display
# CONFIG_RGBINDICATOR=y

#Sense1 add-on option has ST-ISM330DHCX and Bosch-BMP581
# CONFIG_ISM330DHCX=y
# CONFIG_BMP581=y


